[package]
name = "lumi-evals"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
lumi-protocol = { path = "../lumi-protocol" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[lints]
workspace = true
