[package]
name = "lumi-connectors"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
lumi-protocol = { path = "../lumi-protocol" }
lumi-secrets = { path = "../lumi-secrets" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
serde_json = { version = "1", features = ["preserve_order"] }

[lints]
workspace = true
